name: BuildAndRelease

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        javac -Xdiags:verbose -sourcepath src -d classes src/texteditor/Main.java
        jar cvfm texteditor.jar META-INF/MANIFEST.MF -C classes . resources/*
    - name: Upload Release Asset
      uses: marvinpinto/action-automatic-releases@v0.2.2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        prerelease: true
        automatic_release_tag: prerelease
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: prerelease
        prerelease: true
        name: "test automation release with custom name" 
        body: "test change body option." 
        artifacts: "texteditor.jar"
token: ${{ secrets.GITHUB_TOKEN }}