name: BuildAndRelease

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: | 
        javac -Xdiags:verbose -sourcepath src -d classes src/texteditor/Main.java
        jar cvfm texteditor.jar META-INF/MANIFEST.MF -C classes . resources/*
    - name: Just Test
      run: | 
        dir
        cat /etc/os-release
    - name: Upload Release Asset
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        tag: prerelease
        prerelease: true
        artifacts: "texteditor.jar"
        token: ${{ secrets.GITHUB_TOKEN }}
